#!/bin/bash

# VIMFRESH: an easy -hopefully- customization for shell and vim users.
# Copyright (C) 2017  Esteban Murchio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function fresh() {
    local s=$(find ~ -mount -name 'fresh.sh' 2> /dev/null)
    if [[ "$s" == "" ]]; then
        printf "VIMFRESH script not found.\nYou can clone the repo @ https://github.com/estebanmurchio/vimfresh.\n"
        return 1
    fi
    . $s $@
}

function ckdir() { mkdir $1; cd $1; }
function brewup() { brew update; brew upgrade; brew prune; brew cleanup; brew doctor; }
function cask() { brew cask install --appdir="~/Applications" $@; }

alias ls=' ls -GFh'
alias ll=' ls -l'
alias lala=' ls -la'
alias la=' ls -a'
