#!/bin/bash

# VIMFRESH: an easy -hopefully- customization for shell and vim users.
# Copyright (C) 2017  Esteban Murchio
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Homebrew cask default appdir
export HOMEBREW_CASK_OPTS="--appdir=~/Applications"

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
fi
if [ -f /usr/local/etc/bash_completion.d/brew ]; then
    . /usr/local/etc/bash_completion.d/brew
fi
if [ -f /usr/local/etc/bash_completion.d/git-completion.bash ]; then
    . /usr/local/etc/bash_completion.d/git-completion.bash
fi
