alias ls=' ls -GFh'
alias ll=' ls -l'
alias lala=' ls -la'
alias la=' ls -a'
alias g=' cd ~/Documents/git'
alias i=' source ~/.vim/scripts/colors.sh && source ~/.vim/scripts/prompt.sh'

export TERM=xterm-256color
export EDITOR="vim"
export HISTSIZE="500"
export HISTCONTROL="ignoreboth"
export HISTIGNORE="clear:history"
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export PS1="\$git_branch\$git_dirty@ \w > "
