runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect() 
call pathogen#helptags()

syntax on

if has("autocmd")
    filetype plugin indent on
endif

let mapleader=","

set hidden

set nowrap
set tabstop=4
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set shiftwidth=4
set shiftround
set showmatch
set ignorecase
set smartcase
set smarttab
set hlsearch
set incsearch

set history=500
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc
set title
set visualbell
set noerrorbells

set nobackup
set noswapfile

no <up> ddkP
no <down> ddp
no <left> <nop>
no <right> <nop>

ino <up> <nop>
ino <down> <nop>
ino <left> <nop>
ino <right> <nop>

vno <up> <nop>
vno <down> <nop>
vno <left> <nop>
vno <right> <nop>

nmap G Gzz
nmap n nzz
nmap N Nzz
nmap } }zz
nmap { {zz

set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣
set list

