runtime bundle/vim-pathogen/autoload/pathogen.vim

execute pathogen#infect()
Helptags

syntax on

if has("autocmd")
    filetype plugin indent on
endif

let mapleader=","

set nocompatible

set hidden

set nowrap
set backspace=indent,eol,start
set autoindent
set copyindent
set number
set tabstop=4 shiftwidth=4 expandtab
set shiftround
set showmatch
set ignorecase
set smartcase
set smarttab
set hlsearch
set incsearch
set wmnu

set history=500
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc
set title
set visualbell
set noerrorbells

set nobackup
set noswapfile

set list listchars=eol:¬,tab:⇥\ ,extends:❭,precedes:❬,space:\ ,trail:⚋
set laststatus=2
set nohlsearch
set relativenumber
set ruler
set cursorline

set t_Co=256

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_python_checkers = ['python', 'pylint', 'pep8', 'pep257']

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:solarized_termcolors=256
set background=dark
colorscheme morning

let g:airline_theme='sol'
let g:airline_powerline_fonts=1

:hi CursorLineNr ctermbg=252 ctermfg=brown
:hi CursorLine cterm=NONE ctermbg=252 ctermfg=NONE
:hi Cursor cterm=None ctermbg=brown ctermfg=252

no <up> ddkP
no <down> ddp
no <left> <nop>
no <right> <nop>

ino <up> <nop>
ino <down> <nop>
ino <left> <nop>
ino <right> <nop>

vno <up> <nop>
vno <down> <nop>
vno <left> <nop>
vno <right> <nop>

nmap G Gzz
nmap n nzz
nmap N Nzz
nmap } }zz
nmap { {zz

